WebStore/ViewModels/CheckoutViewModel.cs
using System.Collections.Generic;
using WebStore.Models;

namespace WebStore.ViewModels
{
    public class CheckoutViewModel
    {
        public List<Product> Products { get; set; }

        public List<int> Quantities { get; set; }

        public decimal Tax { get; set; }

        public decimal Total { get; set; }
    }
}

WebStore/Controllers/CompaniesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Data;
using WebStore.Models;

namespace WebStore.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly StoreContext _context;

        public CompaniesController(StoreContext context)
        {
            _context = context;    
        }

        // GET: Companies
        public async Task<IActionResult> Index()
        {
            return View(await _context.Companies.ToListAsync());
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .SingleOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Website")] Company company)
        {
            if (ModelState.IsValid)
            {
                _context.Add(company);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(company);
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies.SingleOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Website")] Company company)
        {
            if (id != company.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .SingleOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var company = await _context.Companies.SingleOrDefaultAsync(m => m.Id == id);
            _context.Companies.Remove(company);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool CompanyExists(int id)
        {
            return _context.Companies.Any(e => e.Id == id);
        }
    }
}

WebStore/Controllers/ImagesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using WebStore.Data;
using SkiaSharp;
using System.IO;

namespace WebStore.Controllers
{
    public class ImagesController : Controller
    {
        private StoreContext StoreContext { get; }

        public ImagesController(StoreContext storeContext)
        {
            StoreContext = storeContext ?? throw new ArgumentNullException(nameof(storeContext));
        }

        public IActionResult Index(int id)
        {
            var image = StoreContext.Images.Find(id);

            if (image == null)
            {
                return NotFound();
            }

            return File(image.Content, image.MediaType, image.FileName);
        }

        public IActionResult Thumbnail(int id)
        {
            var image = StoreContext.Images.Find(id);

            if (image == null)
            {
                return NotFound();
            }

            var outputStream = new MemoryStream();

            using (var inputStream = new MemoryStream(image.Content))
            {
                ResizeImage(inputStream, outputStream, 150);
            }

            outputStream.Position = 0;

            return File(outputStream, image.MediaType, image.FileName);
        }

        public void ResizeImage(Stream input, Stream output, int size, int quality = 75)
        {
            using (var inputStream = new SKManagedStream(input))
            using (var original = SKBitmap.Decode(inputStream))
            {
                int width, height;

                if (original.Width > original.Height)
                {
                    width = size;
                    height = original.Height * size / original.Width;
                }
                else
                {
                    width = original.Width * size / original.Height;
                    height = size;
                }

                using (var resized = original.Resize(new SKImageInfo(width, height), SKBitmapResizeMethod.Lanczos3))
                {
                    if (resized == null)
                    {
                        return;
                    }

                    using (var image = SKImage.FromBitmap(resized))
                    {
                        image.Encode(SKEncodedImageFormat.Jpeg, quality)
                            .SaveTo(output);
                    }
                }
            }
            return;
        }
    }
}

WebStore/Controllers/StoreItemsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Data;
using WebStore.Models;

namespace WebStore.Controllers
{
    public class StoreItemsController : Controller
    {
        private readonly StoreContext _context;

        public StoreItemsController(StoreContext context)
        {
            _context = context;    
        }

        // GET: StoreItems
        public async Task<IActionResult> Index()
        {
            var storeContext = _context.Products.Include(s => s.Catagory).Include(s => s.Company);
            return View(await storeContext.ToListAsync());
        }

        // GET: StoreItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var storeItem = await _context.Products
                .Include(s => s.Catagory)
                .Include(s => s.Company)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (storeItem == null)
            {
                return NotFound();
            }

            return View(storeItem);
        }

        // GET: StoreItems/Create
        public IActionResult Create()
        {
            ViewData["CatagoryId"] = new SelectList(_context.Catagories, "Id", "Id");
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name");
            return View();
        }

        // POST: StoreItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,CatagoryId,Description,CompanyId")] Product storeItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(storeItem);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["CatagoryId"] = new SelectList(_context.Catagories, "Id", "Id", storeItem.CatagoryId);
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", storeItem.CompanyId);
            return View(storeItem);
        }

        // GET: StoreItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var storeItem = await _context.Products.SingleOrDefaultAsync(m => m.Id == id);
            if (storeItem == null)
            {
                return NotFound();
            }
            ViewData["CatagoryId"] = new SelectList(_context.Catagories, "Id", "Id", storeItem.CatagoryId);
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", storeItem.CompanyId);
            return View(storeItem);
        }

        // POST: StoreItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,CatagoryId,Description,CompanyId")] Product storeItem)
        {
            if (id != storeItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(storeItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StoreItemExists(storeItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["CatagoryId"] = new SelectList(_context.Catagories, "Id", "Id", storeItem.CatagoryId);
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", storeItem.CompanyId);
            return View(storeItem);
        }

        // GET: StoreItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var storeItem = await _context.Products
                .Include(s => s.Catagory)
                .Include(s => s.Company)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (storeItem == null)
            {
                return NotFound();
            }

            return View(storeItem);
        }

        // POST: StoreItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var storeItem = await _context.Products.SingleOrDefaultAsync(m => m.Id == id);
            _context.Products.Remove(storeItem);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool StoreItemExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

WebStore/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>

<p>This application is a Web Store</p>

<h3>Application does not seem to work in Chrome. Use IE or Edge.</h3>

<ul>
    <li>The Registration page will login if in the database or create a new user.</li>
    <li>Access to admin controls are on the bottom nav bar.</li>
    <li>The print page of the confirmation should have bold text with a purple border.</li>
</ul>

WebStore/Views/Home/Administration.cshtml
@{
    ViewData["Title"] = "Administration";
}

<h2>Administration</h2>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebStore</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="StoreItems" asp-action="Index">Store Items</a></li>
                <li><a asp-area="" asp-controller="Companies" asp-action="Index">Companies</a></li>
            </ul>
        </div>
    </div>
</nav>

WebStore/Views/Home/Checkout.cshtml
@using WebStore.ViewModels;
@using WebStore.Controllers;
@model CheckoutViewModel
@{
    var products = Model.Products;
    var quantities = Model.Quantities;
    ViewData["Title"] = "Checkout";
}

<head>
    <link href="~/css/printstyle.css" type="text/css" rel="stylesheet" media="print"/>
</head>

<h2>Checkout</h2>

<div class="container">
        @for (int index = 0; index < products.Count(); index++)
        {
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="media">
                        <div class="media-left">
                            @*@{
                                var image = products[index].ProductImages.FirstOrDefault();
                            }
                            @if (image != null)
                            {
                                <img class="media-object" src="@Url.Action(nameof(ImagesController.Thumbnail), "Images", values: new { id = image.ImageId })" />
                            }
                            else
                            {
                                <img class="media-object" src="~/images/no-image.jpg" />
                            }*@
                        </div>
                        <div class="media-body">
                            <h3 class="media-heading">@Html.DisplayFor(modelItem => products[index].Name)</h3>
                            <h6>@Html.DisplayFor(modelItem => products[index].Description)</h6>
                            <h4>@Html.DisplayFor(modelItem => products[index].Price)</h4>
                            <h1>Quantity: @Html.DisplayFor(modelItem => quantities[index])</h1>
                        </div>
                    </div>
                </div>
            </div>
                                }
                                <h1>@Html.DisplayForModel(Model.Total)</h1>
                                    <form class="form-inline" method="post">
                                        <a asp-area="" asp-controller="Home" asp-action="Confirmation"><input type="button" value="Confirm Purchase" class="btn btn-primary" /></a>
                                    </form>
</div>

WebStore/Views/Home/Confirmation.cshtml
@using WebStore.ViewModels;
@using WebStore.Controllers;
@model CheckoutViewModel
@{
    var products = Model.Products;
    var quantities = Model.Quantities;
    ViewData["Title"] = "Confirmation";
}
<environment names="Development">
    <link href="~/css/printstyle.css" type="text/css" rel="stylesheet" media="print" />
</environment>
<environment names="Staging,Production">
    <link href="~/css/printstyle.css" type="text/css" rel="stylesheet" media="print" />
</environment>

<h2>Confirmation</h2>

<h4>You Bought:</h4>

<div class="container">
    @for (int index = 0; index < products.Count(); index++)
    {
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="media">
                    <div class="media-left">
                        @*@{
                                var image = products[index].ProductImages.FirstOrDefault();
                            }
                            @if (image != null)
                            {
                                <img class="media-object" src="@Url.Action(nameof(ImagesController.Thumbnail), "Images", values: new { id = image.ImageId })" />
                            }
                            else
                            {
                                <img class="media-object" src="~/images/no-image.jpg" />
                            }*@
                    </div>
                    <div class="media-body">
                        <h3 class="media-heading">@Html.DisplayFor(modelItem => products[index].Name)</h3>
                        <h6>@Html.DisplayFor(modelItem => products[index].Description)</h6>
                        <h4>@Html.DisplayFor(modelItem => products[index].Price)</h4>
                        <h1>Quantity: @Html.DisplayFor(modelItem => quantities[index])</h1>
                    </div>
                </div>
            </div>
        </div>
    }
    <h1>@Html.DisplayForModel(Model.Total)</h1>
</div>

WebStore/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>

<address>
    <strong>Application Creator:</strong> <a href="mailto:danielbowen@mail.weber.edu">Daniel Bowen</a><br />
</address>

WebStore/Views/Home/Registration.cshtml
@using WebStore.Models;
@using WebStore.Controllers;
@model User
@{
    ViewData["Title"] = "Registration";
}

<h2>Registration</h2>

<form asp-controller="Home" asp-action="SaveUser">
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Password" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>